### ISSUE TITLE
Cut down number of jobs in the presence of feature branches

### ISSUE THREAD

**Issue by thofma** [oscar-system/OscarDevTools.jl#9]
https://github.com/Nemocas/AbstractAlgebra.jl/pull/805 created 3^4 = 81 jobs, because there are four packages, each with `master`, `latest` and we also had a custom branch with the same name in every repository (on purpose).

I know there are different ways to handle this, but one thing that came to mind was that if I am working on package A on branch #bla, and dependency B has also a branch #bla, then restrict the version for testing B only to B#bla (or maybe B#bla and B#stable) and not to all three B#latest, B#master and #Bla.

This is just one suggestion. Happy to hear what you think about this.

**Comment by fingolfin** [comment]
Agreed. It seems to me that the most relevant things to test are "all master", "all stable", "all matching branch (with fallback to master). Anything else is bonus and should be carefully selected

**Comment by thofma** [comment]
Yes, I like that suggestion. Maybe fallback to master and latest for the "all matching branch" case.

**Comment by benlorenz** [comment]
I implemented some extra features in #8:
- it adds a global axis which is used for all `pkgs` that don't have an explicit `branches` entry to avoid the combinatorial explosion
- testing matching branches is now done only when `<matching>` is specified in the branch-list, to make it more clear (can be used per pkg and globally). This will fall back to master per pkg when no matching branch is found.
  (this means that if there is no matching branch for any other listed pkg it will do the same as specifying `master`)
- there is a `merge` keyword for merging `origin/master` into the checked out projects (LibGit2 doesn't commit that merge by default so the directory will be dirty but that should not really matter for the CI)
- allow running OscarDevTools with julia 1.3

I have also added some defaults for `os`, `julia-version` and `branches` in this repo here that will be used if nothing is specified in the toml (and allows updating these versions here instead of per repo):
```
const default_os = [ "ubuntu-latest" ]
const default_julia = [ "~1.6.0-0" ]
const default_branches = [ "<matching>", "release" ]
```

So with a rather empty config like [here](https://github.com/oscar-system/OscarDevTools.jl/blob/enh/nonjlrepos/test/meta/OscarCI.toml) it will run just the following three jobs (no matching branch was found for Oscar and Singular):
- `Polymake#master,matching: [Oscar#master,Singular#master] - ubuntu-latest, julia ~1.6.0-0`
- `Polymake#master,[Oscar,Singular]#release - ubuntu-latest, julia ~1.6.0-0`
- `Nemo#master - macos-latest, julia ~1.6.0-0`

**Comment by benlorenz** [comment]
Or for a AbstractAlgebra 805 insprired run running with [this](https://github.com/oscar-system/OscarDevTools.jl/blob/enh/nonjlrepos/test/meta/OscarCI-aa805.toml):
- `matching: [Nemo#wbhart#deprecate_coeffs,Oscar#wbhart#deprecate_coeffs,Hecke#wbhart#deprecate_coeffs,Singular#wbhart#deprecate_coeffs] - ubuntu-latest, julia ~1.6.0-0`
- `[Nemo,Oscar,Hecke,Singular]#release - ubuntu-latest, julia ~1.6.0-0`

Please ignore the test results of these jobs as they are not running with the corresponding branch in AbstractAlgebra but will just is that PR to detect the branch name for the other repositories ...

**Comment by thofma** [comment]
I like it.
